import { MigrationInterface, QueryRunner } from "typeorm";

export class MakeDatesOptional1764672152930 implements MigrationInterface {
    name = 'MakeDatesOptional1764672152930'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "audit_logs_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "user_vehicles" DROP CONSTRAINT "user_vehicles_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "user_vehicles" DROP CONSTRAINT "user_vehicles_vehicle_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "vehicles" DROP CONSTRAINT "vehicles_assigned_driver_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "charge_cards" DROP CONSTRAINT "charge_cards_vehicle_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "charge_sessions" DROP CONSTRAINT "charge_sessions_vehicle_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "charge_sessions" DROP CONSTRAINT "charge_sessions_station_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "charge_sessions" DROP CONSTRAINT "charge_sessions_tariff_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "charge_sessions" DROP CONSTRAINT "charge_sessions_created_by_fkey"`);
        await queryRunner.query(`ALTER TABLE "charge_sessions" DROP CONSTRAINT "charge_sessions_charge_card_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "notifications_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "notifications_session_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "odometer_readings" DROP CONSTRAINT "odometer_readings_session_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "odometer_readings" DROP CONSTRAINT "odometer_readings_entered_by_fkey"`);
        await queryRunner.query(`ALTER TABLE "odometer_readings" DROP CONSTRAINT "odometer_readings_vehicle_id_fkey"`);
        await queryRunner.query(`DROP INDEX "public"."idx_users_email"`);
        await queryRunner.query(`DROP INDEX "public"."idx_users_role"`);
        await queryRunner.query(`DROP INDEX "public"."idx_users_is_active"`);
        await queryRunner.query(`DROP INDEX "public"."idx_audit_logs_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_audit_logs_action"`);
        await queryRunner.query(`DROP INDEX "public"."idx_audit_logs_entity"`);
        await queryRunner.query(`DROP INDEX "public"."idx_audit_logs_created_at"`);
        await queryRunner.query(`DROP INDEX "public"."idx_user_vehicles_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_user_vehicles_vehicle_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_vehicles_registration_no"`);
        await queryRunner.query(`DROP INDEX "public"."idx_vehicles_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_vehicles_make_model"`);
        await queryRunner.query(`DROP INDEX "public"."idx_stations_provider"`);
        await queryRunner.query(`DROP INDEX "public"."idx_stations_is_active"`);
        await queryRunner.query(`DROP INDEX "public"."idx_stations_name"`);
        await queryRunner.query(`DROP INDEX "public"."idx_tariffs_is_active"`);
        await queryRunner.query(`DROP INDEX "public"."idx_tariffs_provider"`);
        await queryRunner.query(`DROP INDEX "public"."idx_tariffs_valid_dates"`);
        await queryRunner.query(`DROP INDEX "public"."idx_charge_sessions_vehicle_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_charge_sessions_station_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_charge_sessions_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_charge_sessions_started_at"`);
        await queryRunner.query(`DROP INDEX "public"."idx_charge_sessions_created_by"`);
        await queryRunner.query(`DROP INDEX "public"."idx_charge_sessions_pending"`);
        await queryRunner.query(`DROP INDEX "public"."idx_charge_sessions_vehicle_started"`);
        await queryRunner.query(`DROP INDEX "public"."idx_notifications_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_notifications_session_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_notifications_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_notifications_type"`);
        await queryRunner.query(`DROP INDEX "public"."idx_notifications_created_at"`);
        await queryRunner.query(`DROP INDEX "public"."idx_notifications_queued"`);
        await queryRunner.query(`DROP INDEX "public"."idx_odometer_vehicle_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_odometer_session_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_odometer_reading_at"`);
        await queryRunner.query(`DROP INDEX "public"."idx_odometer_entered_by"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "users_role_check"`);
        await queryRunner.query(`ALTER TABLE "user_vehicles" DROP CONSTRAINT "user_vehicles_role_on_vehicle_check"`);
        await queryRunner.query(`ALTER TABLE "vehicles" DROP CONSTRAINT "vehicles_year_check"`);
        await queryRunner.query(`ALTER TABLE "vehicles" DROP CONSTRAINT "vehicles_battery_capacity_kwh_check"`);
        await queryRunner.query(`ALTER TABLE "vehicles" DROP CONSTRAINT "vehicles_status_check"`);
        await queryRunner.query(`ALTER TABLE "tariffs" DROP CONSTRAINT "tariffs_price_per_kwh_check"`);
        await queryRunner.query(`ALTER TABLE "charge_sessions" DROP CONSTRAINT "charge_sessions_kwh_charged_check"`);
        await queryRunner.query(`ALTER TABLE "charge_sessions" DROP CONSTRAINT "charge_sessions_price_total_check"`);
        await queryRunner.query(`ALTER TABLE "charge_sessions" DROP CONSTRAINT "charge_sessions_status_check"`);
        await queryRunner.query(`ALTER TABLE "charge_sessions" DROP CONSTRAINT "charge_sessions_check"`);
        await queryRunner.query(`ALTER TABLE "charge_sessions" DROP CONSTRAINT "charge_sessions_check1"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "notifications_type_check"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "notifications_status_check"`);
        await queryRunner.query(`ALTER TABLE "odometer_readings" DROP CONSTRAINT "odometer_readings_reading_km_check"`);
        await queryRunner.query(`ALTER TABLE "user_vehicles" DROP CONSTRAINT "user_vehicles_user_id_vehicle_id_key"`);
        await queryRunner.query(`ALTER TABLE "odometer_readings" DROP CONSTRAINT "odometer_readings_vehicle_id_session_id_key"`);
        await queryRunner.query(`COMMENT ON TABLE "users" IS NULL`);
        await queryRunner.query(`COMMENT ON TABLE "audit_logs" IS NULL`);
        await queryRunner.query(`COMMENT ON TABLE "user_vehicles" IS NULL`);
        await queryRunner.query(`COMMENT ON TABLE "vehicles" IS NULL`);
        await queryRunner.query(`COMMENT ON TABLE "stations" IS NULL`);
        await queryRunner.query(`COMMENT ON TABLE "tariffs" IS NULL`);
        await queryRunner.query(`COMMENT ON TABLE "charge_sessions" IS NULL`);
        await queryRunner.query(`COMMENT ON TABLE "notifications" IS NULL`);
        await queryRunner.query(`COMMENT ON TABLE "odometer_readings" IS NULL`);
        await queryRunner.query(`COMMENT ON TABLE "users" IS NULL`);
        await queryRunner.query(`COMMENT ON TABLE "audit_logs" IS NULL`);
        await queryRunner.query(`COMMENT ON TABLE "vehicles" IS NULL`);
        await queryRunner.query(`COMMENT ON TABLE "user_vehicles" IS NULL`);
        await queryRunner.query(`COMMENT ON TABLE "stations" IS NULL`);
        await queryRunner.query(`COMMENT ON TABLE "tariffs" IS NULL`);
        await queryRunner.query(`COMMENT ON TABLE "charge_sessions" IS NULL`);
        await queryRunner.query(`COMMENT ON TABLE "odometer_readings" IS NULL`);
        await queryRunner.query(`COMMENT ON TABLE "notifications" IS NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "users_email_key"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "email" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "password_hash"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "password_hash" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "full_name"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "full_name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "phone"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "phone" character varying`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "role"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "role" character varying NOT NULL DEFAULT 'driver'`);
        await queryRunner.query(`COMMENT ON COLUMN "audit_logs"."changes" IS NULL`);
        await queryRunner.query(`ALTER TABLE "user_vehicles" DROP COLUMN "role_on_vehicle"`);
        await queryRunner.query(`ALTER TABLE "user_vehicles" ADD "role_on_vehicle" character varying NOT NULL DEFAULT 'driver'`);
        await queryRunner.query(`ALTER TABLE "user_vehicles" ALTER COLUMN "assigned_at" DROP DEFAULT`);
        await queryRunner.query(`COMMENT ON COLUMN "vehicles"."battery_capacity_kwh" IS NULL`);
        await queryRunner.query(`ALTER TABLE "vehicles" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "vehicles" ADD "status" character varying NOT NULL DEFAULT 'active'`);
        await queryRunner.query(`COMMENT ON COLUMN "stations"."connector_types" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "tariffs"."time_of_day" IS NULL`);
        await queryRunner.query(`ALTER TABLE "charge_cards" ALTER COLUMN "is_active" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "charge_cards" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "charge_cards" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "charge_cards" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "charge_cards" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "charge_sessions" ALTER COLUMN "started_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "charge_sessions" ALTER COLUMN "ended_at" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "charge_sessions"."kwh_charged" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "charge_sessions"."price_total" IS NULL`);
        await queryRunner.query(`ALTER TABLE "charge_sessions" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "charge_sessions" ADD "status" character varying NOT NULL DEFAULT 'pending_odometer'`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP COLUMN "type"`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD "type" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD "status" character varying NOT NULL DEFAULT 'queued'`);
        await queryRunner.query(`COMMENT ON COLUMN "notifications"."metadata" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "odometer_readings"."distance_from_previous_km" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "odometer_readings"."kwh_per_100km" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "odometer_readings"."cost_per_100km" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "audit_logs"."changes" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "vehicles"."battery_capacity_kwh" IS NULL`);
        await queryRunner.query(`ALTER TABLE "user_vehicles" ALTER COLUMN "assigned_at" DROP DEFAULT`);
        await queryRunner.query(`COMMENT ON COLUMN "stations"."connector_types" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "tariffs"."time_of_day" IS NULL`);
        await queryRunner.query(`ALTER TABLE "charge_cards" ALTER COLUMN "is_active" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "charge_cards" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "charge_cards" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "charge_cards" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "charge_cards" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "charge_sessions" ALTER COLUMN "started_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "charge_sessions" ALTER COLUMN "ended_at" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "charge_sessions"."kwh_charged" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "charge_sessions"."price_total" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "odometer_readings"."distance_from_previous_km" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "odometer_readings"."kwh_per_100km" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "odometer_readings"."cost_per_100km" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "notifications"."metadata" IS NULL`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "FK_bd2726fd31b35443f2245b93ba0" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_vehicles" ADD CONSTRAINT "FK_6bf7b34f58a2cc949c4ffb9e452" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_vehicles" ADD CONSTRAINT "FK_9bebcb9eb7d9a82590764509cbd" FOREIGN KEY ("vehicle_id") REFERENCES "vehicles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vehicles" ADD CONSTRAINT "FK_206dc3b1eaf70992421f45433fa" FOREIGN KEY ("assigned_driver_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "charge_cards" ADD CONSTRAINT "FK_68b9225ba4ace520c88686af5e8" FOREIGN KEY ("vehicle_id") REFERENCES "vehicles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "charge_sessions" ADD CONSTRAINT "FK_88df3d905499608c1a15065db97" FOREIGN KEY ("vehicle_id") REFERENCES "vehicles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "charge_sessions" ADD CONSTRAINT "FK_a10ce41c648c8fd8a432b2ec104" FOREIGN KEY ("charge_card_id") REFERENCES "charge_cards"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "charge_sessions" ADD CONSTRAINT "FK_8d5d59811c615ed80ab83c1e99a" FOREIGN KEY ("station_id") REFERENCES "stations"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "charge_sessions" ADD CONSTRAINT "FK_45def00ec6d0f60af712c222366" FOREIGN KEY ("tariff_id") REFERENCES "tariffs"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "charge_sessions" ADD CONSTRAINT "FK_6c5e3f2989e22cb7697ad9386df" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_9a8a82462cab47c73d25f49261f" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_4623cc3b1dd7a9fcee5eb0ec326" FOREIGN KEY ("session_id") REFERENCES "charge_sessions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "odometer_readings" ADD CONSTRAINT "FK_b22bc006f597b534f6ac4f2ae11" FOREIGN KEY ("vehicle_id") REFERENCES "vehicles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "odometer_readings" ADD CONSTRAINT "FK_0581a3f4f3bc1a782714f3f6abe" FOREIGN KEY ("session_id") REFERENCES "charge_sessions"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "odometer_readings" ADD CONSTRAINT "FK_1e2d253d949bc818efd95e3fee8" FOREIGN KEY ("entered_by") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "odometer_readings" DROP CONSTRAINT "FK_1e2d253d949bc818efd95e3fee8"`);
        await queryRunner.query(`ALTER TABLE "odometer_readings" DROP CONSTRAINT "FK_0581a3f4f3bc1a782714f3f6abe"`);
        await queryRunner.query(`ALTER TABLE "odometer_readings" DROP CONSTRAINT "FK_b22bc006f597b534f6ac4f2ae11"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_4623cc3b1dd7a9fcee5eb0ec326"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_9a8a82462cab47c73d25f49261f"`);
        await queryRunner.query(`ALTER TABLE "charge_sessions" DROP CONSTRAINT "FK_6c5e3f2989e22cb7697ad9386df"`);
        await queryRunner.query(`ALTER TABLE "charge_sessions" DROP CONSTRAINT "FK_45def00ec6d0f60af712c222366"`);
        await queryRunner.query(`ALTER TABLE "charge_sessions" DROP CONSTRAINT "FK_8d5d59811c615ed80ab83c1e99a"`);
        await queryRunner.query(`ALTER TABLE "charge_sessions" DROP CONSTRAINT "FK_a10ce41c648c8fd8a432b2ec104"`);
        await queryRunner.query(`ALTER TABLE "charge_sessions" DROP CONSTRAINT "FK_88df3d905499608c1a15065db97"`);
        await queryRunner.query(`ALTER TABLE "charge_cards" DROP CONSTRAINT "FK_68b9225ba4ace520c88686af5e8"`);
        await queryRunner.query(`ALTER TABLE "vehicles" DROP CONSTRAINT "FK_206dc3b1eaf70992421f45433fa"`);
        await queryRunner.query(`ALTER TABLE "user_vehicles" DROP CONSTRAINT "FK_9bebcb9eb7d9a82590764509cbd"`);
        await queryRunner.query(`ALTER TABLE "user_vehicles" DROP CONSTRAINT "FK_6bf7b34f58a2cc949c4ffb9e452"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "FK_bd2726fd31b35443f2245b93ba0"`);
        await queryRunner.query(`COMMENT ON COLUMN "notifications"."metadata" IS 'JSON data - template variables, retry count, etc.'`);
        await queryRunner.query(`COMMENT ON COLUMN "odometer_readings"."cost_per_100km" IS 'Cost per 100 km in BGN'`);
        await queryRunner.query(`COMMENT ON COLUMN "odometer_readings"."kwh_per_100km" IS 'Energy consumption per 100 km'`);
        await queryRunner.query(`COMMENT ON COLUMN "odometer_readings"."distance_from_previous_km" IS 'Distance traveled since previous reading'`);
        await queryRunner.query(`COMMENT ON COLUMN "charge_sessions"."price_total" IS 'Total price including VAT'`);
        await queryRunner.query(`COMMENT ON COLUMN "charge_sessions"."kwh_charged" IS 'Charged kWh'`);
        await queryRunner.query(`ALTER TABLE "charge_sessions" ALTER COLUMN "ended_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "charge_sessions" ALTER COLUMN "started_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "charge_cards" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "charge_cards" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "charge_cards" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "charge_cards" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "charge_cards" ALTER COLUMN "is_active" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "tariffs"."time_of_day" IS 'Time of day: peak, off-peak, or all-day'`);
        await queryRunner.query(`COMMENT ON COLUMN "stations"."connector_types" IS 'Array of connector types: Type2, CCS, CHAdeMO'`);
        await queryRunner.query(`ALTER TABLE "user_vehicles" ALTER COLUMN "assigned_at" SET DEFAULT now()`);
        await queryRunner.query(`COMMENT ON COLUMN "vehicles"."battery_capacity_kwh" IS 'Battery capacity in kWh'`);
        await queryRunner.query(`COMMENT ON COLUMN "audit_logs"."changes" IS 'JSON object with changes - before and after'`);
        await queryRunner.query(`COMMENT ON COLUMN "odometer_readings"."cost_per_100km" IS 'Cost per 100 km in BGN'`);
        await queryRunner.query(`COMMENT ON COLUMN "odometer_readings"."kwh_per_100km" IS 'Energy consumption per 100 km'`);
        await queryRunner.query(`COMMENT ON COLUMN "odometer_readings"."distance_from_previous_km" IS 'Distance traveled since previous reading'`);
        await queryRunner.query(`COMMENT ON COLUMN "notifications"."metadata" IS 'JSON data - template variables, retry count, etc.'`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD "status" character varying(50) NOT NULL DEFAULT 'queued'`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP COLUMN "type"`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD "type" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "charge_sessions" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "charge_sessions" ADD "status" character varying(50) NOT NULL DEFAULT 'pending_odometer'`);
        await queryRunner.query(`COMMENT ON COLUMN "charge_sessions"."price_total" IS 'Total price including VAT'`);
        await queryRunner.query(`COMMENT ON COLUMN "charge_sessions"."kwh_charged" IS 'Charged kWh'`);
        await queryRunner.query(`ALTER TABLE "charge_sessions" ALTER COLUMN "ended_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "charge_sessions" ALTER COLUMN "started_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "charge_cards" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "charge_cards" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "charge_cards" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "charge_cards" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "charge_cards" ALTER COLUMN "is_active" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "tariffs"."time_of_day" IS 'Time of day: peak, off-peak, or all-day'`);
        await queryRunner.query(`COMMENT ON COLUMN "stations"."connector_types" IS 'Array of connector types: Type2, CCS, CHAdeMO'`);
        await queryRunner.query(`ALTER TABLE "vehicles" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "vehicles" ADD "status" character varying(50) NOT NULL DEFAULT 'active'`);
        await queryRunner.query(`COMMENT ON COLUMN "vehicles"."battery_capacity_kwh" IS 'Battery capacity in kWh'`);
        await queryRunner.query(`ALTER TABLE "user_vehicles" ALTER COLUMN "assigned_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "user_vehicles" DROP COLUMN "role_on_vehicle"`);
        await queryRunner.query(`ALTER TABLE "user_vehicles" ADD "role_on_vehicle" character varying(50) NOT NULL DEFAULT 'driver'`);
        await queryRunner.query(`COMMENT ON COLUMN "audit_logs"."changes" IS 'JSON object with changes - before and after'`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "role"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "role" character varying(50) NOT NULL DEFAULT 'driver'`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "phone"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "phone" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "full_name"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "full_name" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "password_hash"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "password_hash" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "email" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "users_email_key" UNIQUE ("email")`);
        await queryRunner.query(`COMMENT ON TABLE "notifications" IS 'Notifications to users'`);
        await queryRunner.query(`COMMENT ON TABLE "odometer_readings" IS 'Odometer readings for vehicles'`);
        await queryRunner.query(`COMMENT ON TABLE "charge_sessions" IS 'Charging sessions - manually entered by administrators'`);
        await queryRunner.query(`COMMENT ON TABLE "tariffs" IS 'Charging tariffs and pricing'`);
        await queryRunner.query(`COMMENT ON TABLE "stations" IS 'Charging stations'`);
        await queryRunner.query(`COMMENT ON TABLE "user_vehicles" IS 'Assignment of users to vehicles'`);
        await queryRunner.query(`COMMENT ON TABLE "vehicles" IS 'Electric vehicles in the fleet'`);
        await queryRunner.query(`COMMENT ON TABLE "audit_logs" IS 'Audit trail for all critical actions'`);
        await queryRunner.query(`COMMENT ON TABLE "users" IS 'Default password for all users: Password123!'`);
        await queryRunner.query(`COMMENT ON TABLE "odometer_readings" IS 'Odometer readings for vehicles'`);
        await queryRunner.query(`COMMENT ON TABLE "notifications" IS 'Notifications to users'`);
        await queryRunner.query(`COMMENT ON TABLE "charge_sessions" IS 'Charging sessions - manually entered by administrators'`);
        await queryRunner.query(`COMMENT ON TABLE "tariffs" IS 'Charging tariffs and pricing'`);
        await queryRunner.query(`COMMENT ON TABLE "stations" IS 'Charging stations'`);
        await queryRunner.query(`COMMENT ON TABLE "vehicles" IS 'Electric vehicles in the fleet'`);
        await queryRunner.query(`COMMENT ON TABLE "user_vehicles" IS 'Assignment of users to vehicles'`);
        await queryRunner.query(`COMMENT ON TABLE "audit_logs" IS 'Audit trail for all critical actions'`);
        await queryRunner.query(`COMMENT ON TABLE "users" IS 'Default password for all users: Password123!'`);
        await queryRunner.query(`ALTER TABLE "odometer_readings" ADD CONSTRAINT "odometer_readings_vehicle_id_session_id_key" UNIQUE ("vehicle_id", "session_id")`);
        await queryRunner.query(`ALTER TABLE "user_vehicles" ADD CONSTRAINT "user_vehicles_user_id_vehicle_id_key" UNIQUE ("user_id", "vehicle_id")`);
        await queryRunner.query(`ALTER TABLE "odometer_readings" ADD CONSTRAINT "odometer_readings_reading_km_check" CHECK ((reading_km >= 0))`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "notifications_status_check" CHECK (((status)::text = ANY ((ARRAY['queued'::character varying, 'sent'::character varying, 'failed'::character varying, 'seen'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "notifications_type_check" CHECK (((type)::text = ANY ((ARRAY['odometer_request'::character varying, 'odometer_reminder'::character varying, 'report_ready'::character varying, 'system'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "charge_sessions" ADD CONSTRAINT "charge_sessions_check1" CHECK (((kwh_charged > (0)::numeric) OR ((status)::text = 'cancelled'::text)))`);
        await queryRunner.query(`ALTER TABLE "charge_sessions" ADD CONSTRAINT "charge_sessions_check" CHECK ((ended_at >= started_at))`);
        await queryRunner.query(`ALTER TABLE "charge_sessions" ADD CONSTRAINT "charge_sessions_status_check" CHECK (((status)::text = ANY ((ARRAY['pending_odometer'::character varying, 'completed'::character varying, 'cancelled'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "charge_sessions" ADD CONSTRAINT "charge_sessions_price_total_check" CHECK ((price_total >= (0)::numeric))`);
        await queryRunner.query(`ALTER TABLE "charge_sessions" ADD CONSTRAINT "charge_sessions_kwh_charged_check" CHECK ((kwh_charged >= (0)::numeric))`);
        await queryRunner.query(`ALTER TABLE "tariffs" ADD CONSTRAINT "tariffs_price_per_kwh_check" CHECK ((price_per_kwh >= (0)::numeric))`);
        await queryRunner.query(`ALTER TABLE "vehicles" ADD CONSTRAINT "vehicles_status_check" CHECK (((status)::text = ANY ((ARRAY['active'::character varying, 'maintenance'::character varying, 'retired'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "vehicles" ADD CONSTRAINT "vehicles_battery_capacity_kwh_check" CHECK ((battery_capacity_kwh > (0)::numeric))`);
        await queryRunner.query(`ALTER TABLE "vehicles" ADD CONSTRAINT "vehicles_year_check" CHECK (((year >= 2000) AND (year <= 2100)))`);
        await queryRunner.query(`ALTER TABLE "user_vehicles" ADD CONSTRAINT "user_vehicles_role_on_vehicle_check" CHECK (((role_on_vehicle)::text = ANY ((ARRAY['primary_driver'::character varying, 'driver'::character varying, 'responsible'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "users_role_check" CHECK (((role)::text = ANY ((ARRAY['admin'::character varying, 'fleet_manager'::character varying, 'driver'::character varying])::text[])))`);
        await queryRunner.query(`CREATE INDEX "idx_odometer_entered_by" ON "odometer_readings" ("entered_by") `);
        await queryRunner.query(`CREATE INDEX "idx_odometer_reading_at" ON "odometer_readings" ("vehicle_id", "reading_at") `);
        await queryRunner.query(`CREATE INDEX "idx_odometer_session_id" ON "odometer_readings" ("session_id") `);
        await queryRunner.query(`CREATE INDEX "idx_odometer_vehicle_id" ON "odometer_readings" ("vehicle_id") `);
        await queryRunner.query(`CREATE INDEX "idx_notifications_queued" ON "notifications" ("status", "created_at") WHERE ((status)::text = 'queued'::text)`);
        await queryRunner.query(`CREATE INDEX "idx_notifications_created_at" ON "notifications" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "idx_notifications_type" ON "notifications" ("type") `);
        await queryRunner.query(`CREATE INDEX "idx_notifications_status" ON "notifications" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_notifications_session_id" ON "notifications" ("session_id") `);
        await queryRunner.query(`CREATE INDEX "idx_notifications_user_id" ON "notifications" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_charge_sessions_vehicle_started" ON "charge_sessions" ("vehicle_id", "started_at") `);
        await queryRunner.query(`CREATE INDEX "idx_charge_sessions_pending" ON "charge_sessions" ("vehicle_id", "status") WHERE ((status)::text = 'pending_odometer'::text)`);
        await queryRunner.query(`CREATE INDEX "idx_charge_sessions_created_by" ON "charge_sessions" ("created_by") `);
        await queryRunner.query(`CREATE INDEX "idx_charge_sessions_started_at" ON "charge_sessions" ("started_at") `);
        await queryRunner.query(`CREATE INDEX "idx_charge_sessions_status" ON "charge_sessions" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_charge_sessions_station_id" ON "charge_sessions" ("station_id") `);
        await queryRunner.query(`CREATE INDEX "idx_charge_sessions_vehicle_id" ON "charge_sessions" ("vehicle_id") `);
        await queryRunner.query(`CREATE INDEX "idx_tariffs_valid_dates" ON "tariffs" ("valid_from", "valid_until") `);
        await queryRunner.query(`CREATE INDEX "idx_tariffs_provider" ON "tariffs" ("provider") `);
        await queryRunner.query(`CREATE INDEX "idx_tariffs_is_active" ON "tariffs" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "idx_stations_name" ON "stations" ("name") `);
        await queryRunner.query(`CREATE INDEX "idx_stations_is_active" ON "stations" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "idx_stations_provider" ON "stations" ("provider") `);
        await queryRunner.query(`CREATE INDEX "idx_vehicles_make_model" ON "vehicles" ("make", "model") `);
        await queryRunner.query(`CREATE INDEX "idx_vehicles_status" ON "vehicles" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_vehicles_registration_no" ON "vehicles" ("registration_no") `);
        await queryRunner.query(`CREATE INDEX "idx_user_vehicles_vehicle_id" ON "user_vehicles" ("vehicle_id") `);
        await queryRunner.query(`CREATE INDEX "idx_user_vehicles_user_id" ON "user_vehicles" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_audit_logs_created_at" ON "audit_logs" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "idx_audit_logs_entity" ON "audit_logs" ("entity_type", "entity_id") `);
        await queryRunner.query(`CREATE INDEX "idx_audit_logs_action" ON "audit_logs" ("action") `);
        await queryRunner.query(`CREATE INDEX "idx_audit_logs_user_id" ON "audit_logs" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_users_is_active" ON "users" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "idx_users_role" ON "users" ("role") `);
        await queryRunner.query(`CREATE INDEX "idx_users_email" ON "users" ("email") `);
        await queryRunner.query(`ALTER TABLE "odometer_readings" ADD CONSTRAINT "odometer_readings_vehicle_id_fkey" FOREIGN KEY ("vehicle_id") REFERENCES "vehicles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "odometer_readings" ADD CONSTRAINT "odometer_readings_entered_by_fkey" FOREIGN KEY ("entered_by") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "odometer_readings" ADD CONSTRAINT "odometer_readings_session_id_fkey" FOREIGN KEY ("session_id") REFERENCES "charge_sessions"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "notifications_session_id_fkey" FOREIGN KEY ("session_id") REFERENCES "charge_sessions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "notifications_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "charge_sessions" ADD CONSTRAINT "charge_sessions_charge_card_id_fkey" FOREIGN KEY ("charge_card_id") REFERENCES "charge_cards"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "charge_sessions" ADD CONSTRAINT "charge_sessions_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "charge_sessions" ADD CONSTRAINT "charge_sessions_tariff_id_fkey" FOREIGN KEY ("tariff_id") REFERENCES "tariffs"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "charge_sessions" ADD CONSTRAINT "charge_sessions_station_id_fkey" FOREIGN KEY ("station_id") REFERENCES "stations"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "charge_sessions" ADD CONSTRAINT "charge_sessions_vehicle_id_fkey" FOREIGN KEY ("vehicle_id") REFERENCES "vehicles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "charge_cards" ADD CONSTRAINT "charge_cards_vehicle_id_fkey" FOREIGN KEY ("vehicle_id") REFERENCES "vehicles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vehicles" ADD CONSTRAINT "vehicles_assigned_driver_id_fkey" FOREIGN KEY ("assigned_driver_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_vehicles" ADD CONSTRAINT "user_vehicles_vehicle_id_fkey" FOREIGN KEY ("vehicle_id") REFERENCES "vehicles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_vehicles" ADD CONSTRAINT "user_vehicles_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "audit_logs_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

}
